---
swagger: '2.0'
info:
  version: v1
  title: Invite Microservice
  description: Invite API
paths:
  "/api/Users":
    get:
      tags:
      - Users
      operationId: ApiUsersGet
      consumes: []
      produces:
      - text/plain
      - application/json
      - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              "$ref": "#/definitions/User"
        

    post:
      tags:
      - Users
      operationId: ApiUsersPost
      consumes:
      - application/json-patch+json
      - application/json
      - text/json
      - application/*+json
      produces: []
      parameters:
      - name: value
        in: body
        required: false
        schema:
          $ref: '#definitions/UserEmail'
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorised
  "/api/Users/verify":
    post:
      tags:
      - Users
      operationId: ApiUsersVerifyPost
      consumes:
      - application/json-patch+json
      - application/json
      - text/json
      - application/*+json
      produces: []
      parameters:
      - name: value
        in: body
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
#   "/api/Values":
#     get:
#       tags:
#       - Values
#       operationId: ApiValuesGet
#       consumes: []
#       produces:
#       - text/plain
#       - application/json
#       - text/json
#       parameters: []
#       responses:
#         '200':
#           description: Success
#           schema:
#             uniqueItems: false
#             type: array
#             items:
#               type: string
#     post:
#       tags:
#       - Values
#       operationId: ApiValuesPost
#       consumes:
#       - application/json-patch+json
#       - application/json
#       - text/json
#       - application/*+json
#       produces: []
#       parameters:
#       - name: value
#         in: body
#         required: false
#         schema:
#           type: string
#       responses:
#         '200':
#           description: Success
#   "/api/Values/{id}":
#     get:
#       tags:
#       - Values
#       operationId: ApiValuesByIdGet
#       consumes: []
#       produces:
#       - text/plain
#       - application/json
#       - text/json
#       parameters:
#       - name: id
#         in: path
#         required: true
#         type: integer
#         format: int32
#       responses:
#         '200':
#           description: Success
#           schema:
#             type: string
#     put:
#       tags:
#       - Values
#       operationId: ApiValuesByIdPut
#       consumes:
#       - application/json-patch+json
#       - application/json
#       - text/json
#       - application/*+json
#       produces: []
#       parameters:
#       - name: id
#         in: path
#         required: true
#         type: integer
#         format: int32
#       - name: value
#         in: body
#         required: false
#         schema:
#           type: string
#       responses:
#         '200':
#           description: Success
#     delete:
#       tags:
#       - Values
#       operationId: ApiValuesByIdDelete
#       consumes: []
#       produces: []
#       parameters:
#       - name: id
#         in: path
#         required: true
#         type: integer
#         format: int32
#       responses:
#         '200':
#           description: Success
definitions:
  User:
    type: object
    properties:
      id:
        format: int32
        type: integer
      email:
        type: string
      token:
        type: string
  UserEmail:
    type: object
    properties:
      email:
        type: string
        format: email
